# Generated by Django 4.0.5 on 2022-08-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='tiempo',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
