# Generated by Django 4.0.5 on 2022-07-11 06:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('i', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=20, verbose_name='Nombre completo')),
                ('curso', models.TextField(max_length=20, verbose_name='Nombre del curso')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('tiempo', models.BooleanField(default=False, verbose_name='Deseas obtener el curso intensivo')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Descripción de la actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Descripciones',
                'verbose_name_plural': 'Descripción',
                'ordering': ['-created'],
            },
        ),
    ]
